#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ $# -le 4 ]
then
    if [ $# -le 3 ]
    then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
    fi
    if [ $# -eq 4 ]
    then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":
    fi
fi
