#!/usr/bin/env bash
# Installing a nginx to a remote web server!
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://youtu.be/VZG8BnuwtZU permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
