#!/usr/bin/env bash
# Installing a nginx to a remote web server!
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404_index.html
sed -i "/listen 80 default_server/a add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://youtu.be/VZG8BnuwtZU permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /404_index.html; location = /404_index.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
sudo service nginx start
