#!/usr/bin/env bash
# Bash script that configures HAproxy on server
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
sudo sed -i '$ a\\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver gc-1259-web-01-1585001773 35.231.14.240:80\n\tserver 1259-web-02 34.229.216.161:80' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
