#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, 9th iteration display hi
i=1
while [ $i -lt 11 ]
do
    echo 'Holberton School'
if [ $i -eq 9 ]
then
    echo 'Hi'
fi
    ((i++))
done
