#!/usr/bin/env bash
# Scipt so Nginx runs as nginx user
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80 default/8080/ default" /etc/nginx/sites-available/default
sudo chmod -R 755 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start
